name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.2.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^4.2.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  google_mlkit_text_recognition: ^0.11.0
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
